name: assignment-6

services:
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db  
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - db  
    environment:
      - MONGO_URL=mongodb://db:27017/assignment6
    networks:
      - app-network

volumes:
  mongo-data: 

networks:
  app-network:
    driver: bridge
